/**
 * Upload files directly to S3 from the browser, using presigned URLs generated by the
 * `bref/laravel-bridge` package (see the `uploads` section of `config/bref.php`).
 *
 * This module has no dependencies and works with any frontend framework. It can be used in two ways:
 *
 * 1. Import it from the Composer package, so that it always matches the installed version of the
 *    package. With Vite, add an alias in `vite.config.js`:
 *
 *        resolve: {
 *            alias: {
 *                'bref-upload': path.resolve('vendor/bref/laravel-bridge/resources/js/bref-upload.js'),
 *            },
 *        },
 *
 *    and import it with `import { upload } from 'bref-upload';`.
 *
 * 2. Copy it into your application with `php artisan vendor:publish --tag=bref-upload`, which puts it in
 *    `resources/js/bref-upload.js`. You own the copy: it will not change when the package is updated.
 *
 * @example
 *     import { upload } from 'bref-upload';
 *
 *     const { key } = await upload(file, {
 *         progress: (ratio) => console.log(`${Math.round(ratio * 100)}%`),
 *     });
 *     // Send `key` to the backend, validate it with the `UploadedToS3` rule
 */

/**
 * @typedef {Object} SignedUpload
 * @property {string} uuid The unique ID of the upload.
 * @property {string} key The S3 key of the uploaded file, to send to the backend.
 * @property {string} bucket The S3 bucket.
 * @property {string} url The presigned URL the file was uploaded to.
 * @property {Object<string, string>} headers The headers used for the upload.
 * @property {string|null} extension The file extension derived from the content type, or null if unknown.
 */

/**
 * @typedef {Object} UploadOptions
 * @property {string} [url] URL of the backend route returning signed upload URLs. Defaults to `/signed-upload-url`.
 * @property {string} [contentType] MIME type of the file. Defaults to `file.type`, or `application/octet-stream`.
 * @property {(ratio: number) => void} [progress] Called with the upload progress, from 0 to 1.
 * @property {Object<string, string>} [headers] Extra headers to send to the backend route (e.g. `Authorization`).
 * @property {string} [csrfToken] CSRF token. Defaults to the content of the `<meta name="csrf-token">` tag.
 * @property {AbortSignal} [signal] Signal to cancel the upload.
 */

/**
 * Error thrown when the upload fails. `status` is the HTTP status code of the failed request (0 on network errors).
 */
export class UploadError extends Error {
    /**
     * @param {string} message
     * @param {number} status
     */
    constructor(message, status) {
        super(message);
        this.name = 'UploadError';
        this.status = status;
    }
}

/**
 * Upload a file to S3.
 *
 * @param {File|Blob} file
 * @param {UploadOptions} [options]
 * @returns {Promise<SignedUpload>}
 */
export async function upload(file, options = {}) {
    const url = options.url ?? '/signed-upload-url';
    const contentType = options.contentType || file.type || 'application/octet-stream';
    const csrfToken = options.csrfToken ?? readCsrfToken();

    const headers = {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
        ...(csrfToken ? { 'X-CSRF-TOKEN': csrfToken } : {}),
        ...(options.headers ?? {}),
    };

    const response = await fetch(url, {
        method: 'POST',
        headers,
        body: JSON.stringify({ content_type: contentType }),
        credentials: 'same-origin',
        signal: options.signal,
    });

    if (!response.ok) {
        throw new UploadError(`Could not get a signed upload URL (HTTP ${response.status}).`, response.status);
    }

    /** @type {SignedUpload} */
    const signed = await response.json();

    await putToS3(file, signed, contentType, options.progress, options.signal);

    return signed;
}

/**
 * Alias of `upload()`, with the same result shape and progress callback as Laravel Vapor's `Vapor.store()`.
 * Only the UploadOptions documented above are supported; Vapor-specific options are not interpreted.
 */
export const store = upload;

export default { upload, store, UploadError };

/**
 * @param {File|Blob} file
 * @param {SignedUpload} signed
 * @param {string} contentType
 * @param {((ratio: number) => void)|undefined} progress
 * @param {AbortSignal|undefined} signal
 * @returns {Promise<void>}
 */
function putToS3(file, signed, contentType, progress, signal) {
    return new Promise((resolve, reject) => {
        if (signal?.aborted) {
            reject(abortError());
            return;
        }

        const xhr = new XMLHttpRequest();
        xhr.open('PUT', signed.url);

        let hasContentType = false;
        for (const [name, value] of Object.entries(signed.headers ?? {})) {
            // Browsers forbid setting the Host header
            if (name.toLowerCase() === 'host') {
                continue;
            }
            if (name.toLowerCase() === 'content-type') {
                hasContentType = true;
            }
            xhr.setRequestHeader(name, value);
        }
        if (!hasContentType) {
            xhr.setRequestHeader('Content-Type', contentType);
        }

        if (progress) {
            xhr.upload.addEventListener('progress', (event) => {
                if (event.lengthComputable) {
                    progress(event.loaded / event.total);
                }
            });
        }

        xhr.addEventListener('load', () => {
            if (xhr.status >= 200 && xhr.status < 300) {
                if (progress) {
                    progress(1);
                }
                resolve();
            } else {
                reject(new UploadError(`The upload to S3 failed (HTTP ${xhr.status}).`, xhr.status));
            }
        });
        xhr.addEventListener('error', () => {
            reject(new UploadError('The upload to S3 failed (network error). Check the CORS configuration of the bucket.', 0));
        });
        xhr.addEventListener('abort', () => reject(abortError()));

        const onAbort = () => xhr.abort();
        const cleanup = () => signal?.removeEventListener('abort', onAbort);
        if (signal) {
            signal.addEventListener('abort', onAbort, { once: true });
            xhr.addEventListener('loadend', cleanup, { once: true });
        }

        try {
            xhr.send(file);
        } catch (error) {
            cleanup();
            reject(error);
        }
    });
}

/**
 * @returns {string|undefined}
 */
function readCsrfToken() {
    if (typeof document === 'undefined') {
        return undefined;
    }

    return document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') ?? undefined;
}

/**
 * @returns {Error}
 */
function abortError() {
    if (typeof DOMException !== 'undefined') {
        return new DOMException('The upload was aborted.', 'AbortError');
    }

    const error = new Error('The upload was aborted.');
    error.name = 'AbortError';
    return error;
}
