/**
 * Upload files directly to S3 from the browser, using presigned URLs generated by the
 * `bref/laravel-bridge` package (see the `uploads` section of `config/bref.php`).
 *
 * This module has no dependencies and works with any frontend framework. It can be used in two ways:
 *
 * 1. Import it from the Composer package, so that it always matches the installed version of the
 *    package. With Vite, add an alias in `vite.config.js`:
 *
 *        resolve: {
 *            alias: {
 *                'bref-upload': path.resolve('vendor/bref/laravel-bridge/resources/js/bref-upload.js'),
 *            },
 *        },
 *
 *    and import it with `import { upload } from 'bref-upload';`.
 *
 * 2. Copy it into your application with `php artisan vendor:publish --tag=bref-upload`, which puts it in
 *    `resources/js/bref-upload.js`. You own the copy: it will not change when the package is updated.
 *
 * @example
 *     import { upload } from 'bref-upload';
 *
 *     const { key } = await upload(file, {
 *         progress: (ratio) => console.log(`${Math.round(ratio * 100)}%`),
 *     });
 *     // Send `key` to the backend, validate it with the `UploadedToS3` rule
 */

/**
 * @typedef {Object} SignedUpload
 * @property {string} uuid The unique ID of the upload.
 * @property {string} key The S3 key of the uploaded file, to send to the backend.
 * @property {string} bucket The S3 bucket.
 * @property {string} url The presigned URL the file was uploaded to.
 * @property {Object<string, string>} headers The headers used for the upload.
 * @property {string|null} extension The file extension derived from the content type, or null if unknown.
 */

/**
 * @typedef {Object} UploadOptions
 * @property {string} [url] URL of the backend route returning signed upload URLs. Defaults to `/signed-upload-url`.
 * @property {string} [contentType] MIME type of the file. Defaults to `file.type`, or `application/octet-stream`.
 * @property {(ratio: number) => void} [progress] Called with the upload progress, from 0 to 1.
 * @property {Object<string, string>} [headers] Extra headers to send to the backend route (e.g. `Authorization`).
 * @property {string} [csrfToken] CSRF token, sent as `X-CSRF-TOKEN`. By default, for same-origin requests, the
 *     `XSRF-TOKEN` cookie set by Laravel is sent as `X-XSRF-TOKEN` (like axios and Inertia do), or else the content
 *     of the `<meta name="csrf-token">` tag is sent as `X-CSRF-TOKEN`.
 * @property {AbortSignal} [signal] Signal to cancel the upload.
 * @property {HttpClient} [httpClient] An axios-compatible HTTP client to use instead of `fetch` and `XMLHttpRequest`.
 *     The client is then responsible for CSRF and authentication.
 */

/**
 * An axios-compatible HTTP client (`axios` itself, or an axios instance).
 *
 * @typedef {Object} HttpClient
 * @property {(url: string, data: any, config: Object) => Promise<{ data: any }>} post
 * @property {(url: string, data: any, config: Object) => Promise<any>} put
 */

/**
 * Error thrown when the upload fails. `status` is the HTTP status code of the failed request (0 on network errors).
 */
export class UploadError extends Error {
    /**
     * @param {string} message
     * @param {number} status
     */
    constructor(message, status) {
        super(message);
        this.name = 'UploadError';
        this.status = status;
    }
}

/**
 * Upload a file to S3.
 *
 * @param {File|Blob} file
 * @param {UploadOptions} [options]
 * @returns {Promise<SignedUpload>}
 */
export async function upload(file, options = {}) {
    const url = options.url ?? '/signed-upload-url';
    const contentType = options.contentType || file.type || 'application/octet-stream';

    if (options.httpClient) {
        return uploadWithHttpClient(file, url, contentType, options);
    }

    const headers = {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
        ...csrfHeaders(url, options.csrfToken),
        ...(options.headers ?? {}),
    };

    const response = await fetch(url, {
        method: 'POST',
        headers,
        body: JSON.stringify({ content_type: contentType }),
        credentials: 'same-origin',
        signal: options.signal,
    });

    if (!response.ok) {
        throw new UploadError(`Could not get a signed upload URL (HTTP ${response.status}).`, response.status);
    }

    /** @type {SignedUpload} */
    const signed = await response.json();

    await putToS3(file, signed, contentType, options.progress, options.signal);

    return signed;
}

/**
 * Alias of `upload()`, with the same result shape and progress callback as Laravel Vapor's `Vapor.store()`.
 * Only the UploadOptions documented above are supported; Vapor-specific options are not interpreted.
 */
export const store = upload;

export default { upload, store, UploadError };

/**
 * Same as `upload()`, but delegating both requests to an axios-compatible client.
 *
 * @param {File|Blob} file
 * @param {string} url
 * @param {string} contentType
 * @param {UploadOptions} options
 * @returns {Promise<SignedUpload>}
 */
async function uploadWithHttpClient(file, url, contentType, options) {
    const { httpClient, progress, signal } = options;

    /** @type {SignedUpload} */
    let signed;
    try {
        const response = await httpClient.post(url, { content_type: contentType }, {
            headers: options.headers ?? {},
            signal,
        });
        signed = response.data;
    } catch (error) {
        throw wrapHttpClientError(error, 'Could not get a signed upload URL');
    }

    try {
        await httpClient.put(signed.url, file, {
            headers: uploadHeaders(signed, contentType),
            signal,
            onUploadProgress: (event) => {
                if (progress && event.total) {
                    progress(event.loaded / event.total);
                }
            },
        });
    } catch (error) {
        throw wrapHttpClientError(error, 'The upload to S3 failed');
    }

    if (progress) {
        progress(1);
    }

    return signed;
}

/**
 * Converts an error thrown by an axios-compatible client into an `UploadError` (cancellations are rethrown as is).
 *
 * @param {any} error
 * @param {string} message
 * @returns {Error}
 */
function wrapHttpClientError(error, message) {
    if (error?.code === 'ERR_CANCELED' || error?.name === 'CanceledError' || error?.name === 'AbortError') {
        return error;
    }

    const status = error?.response?.status ?? 0;
    const uploadError = new UploadError(`${message} (HTTP ${status}).`, status);
    uploadError.cause = error;

    return uploadError;
}

/**
 * The headers to send along with the file to S3: the presigned headers (except `Host`, which browsers forbid)
 * and the content type.
 *
 * @param {SignedUpload} signed
 * @param {string} contentType
 * @returns {Object<string, string>}
 */
function uploadHeaders(signed, contentType) {
    const headers = {};
    let hasContentType = false;

    for (const [name, value] of Object.entries(signed.headers ?? {})) {
        if (name.toLowerCase() === 'host') {
            continue;
        }
        if (name.toLowerCase() === 'content-type') {
            hasContentType = true;
        }
        headers[name] = value;
    }
    if (!hasContentType) {
        headers['Content-Type'] = contentType;
    }

    return headers;
}

/**
 * @param {File|Blob} file
 * @param {SignedUpload} signed
 * @param {string} contentType
 * @param {((ratio: number) => void)|undefined} progress
 * @param {AbortSignal|undefined} signal
 * @returns {Promise<void>}
 */
function putToS3(file, signed, contentType, progress, signal) {
    return new Promise((resolve, reject) => {
        if (signal?.aborted) {
            reject(abortError());
            return;
        }

        const xhr = new XMLHttpRequest();
        xhr.open('PUT', signed.url);

        for (const [name, value] of Object.entries(uploadHeaders(signed, contentType))) {
            xhr.setRequestHeader(name, value);
        }

        if (progress) {
            xhr.upload.addEventListener('progress', (event) => {
                if (event.lengthComputable) {
                    progress(event.loaded / event.total);
                }
            });
        }

        xhr.addEventListener('load', () => {
            if (xhr.status >= 200 && xhr.status < 300) {
                if (progress) {
                    progress(1);
                }
                resolve();
            } else {
                reject(new UploadError(`The upload to S3 failed (HTTP ${xhr.status}).`, xhr.status));
            }
        });
        xhr.addEventListener('error', () => {
            reject(new UploadError('The upload to S3 failed (network error). Check the CORS configuration of the bucket.', 0));
        });
        xhr.addEventListener('abort', () => reject(abortError()));

        const onAbort = () => xhr.abort();
        const cleanup = () => signal?.removeEventListener('abort', onAbort);
        if (signal) {
            signal.addEventListener('abort', onAbort, { once: true });
            xhr.addEventListener('loadend', cleanup, { once: true });
        }

        try {
            xhr.send(file);
        } catch (error) {
            cleanup();
            reject(error);
        }
    });
}

/**
 * The CSRF header(s) to send to the backend route.
 *
 * An explicit token is always sent. Otherwise, the token is only sent to same-origin URLs (like axios does), reading
 * the `XSRF-TOKEN` cookie first because it is always up to date, and the `<meta name="csrf-token">` tag otherwise.
 *
 * @param {string} url
 * @param {string|undefined} csrfToken
 * @returns {Object<string, string>}
 */
function csrfHeaders(url, csrfToken) {
    if (csrfToken) {
        return { 'X-CSRF-TOKEN': csrfToken };
    }

    if (typeof document === 'undefined' || !isSameOrigin(url)) {
        return {};
    }

    const xsrfToken = readCookie('XSRF-TOKEN');
    if (xsrfToken) {
        return { 'X-XSRF-TOKEN': xsrfToken };
    }

    const metaToken = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content');
    if (metaToken) {
        return { 'X-CSRF-TOKEN': metaToken };
    }

    return {};
}

/**
 * @param {string} url
 * @returns {boolean}
 */
function isSameOrigin(url) {
    if (typeof window === 'undefined' || !window.location) {
        return false;
    }

    try {
        return new URL(url, window.location.href).origin === window.location.origin;
    } catch {
        return false;
    }
}

/**
 * @param {string} name
 * @returns {string|undefined}
 */
function readCookie(name) {
    const match = document.cookie.match(new RegExp('(?:^|;\\s*)' + name + '=([^;]*)'));

    return match ? decodeURIComponent(match[1]) : undefined;
}

/**
 * @returns {Error}
 */
function abortError() {
    if (typeof DOMException !== 'undefined') {
        return new DOMException('The upload was aborted.', 'AbortError');
    }

    const error = new Error('The upload was aborted.');
    error.name = 'AbortError';
    return error;
}
